services:

  api:
    build:
      context: .
    container_name: api-ec2-simulate-test
    ports:
      - "8080:8080"
    networks:
      - localstack-net

networks:
  localstack-net:
    external: true